# Adaline

### 1. How to create a class
### 2. how to create object of a class
### 3. how to define a metod

In [5]:
# create 2 Numreical Arrays and apply dot product
import numpy as np

In [6]:
a=np.array([[2,3],[4,5]])
b=np.array([[6,5],[4,8]])
print(a+b)

[[ 8  8]
 [ 8 13]]


In [7]:
prod = np.dot(a,b)

In [8]:
prod

array([[24, 34],
       [44, 60]])

In [9]:
print(a*b)

[[12 15]
 [16 40]]


In [10]:
def hello():
    print("welcome to MCA")

In [11]:
hello()

welcome to MCA


In [12]:
def funct(x):
    if(x%2 == 0):
        print("EVEN")
    else:
        print("ODD")

In [13]:
funct(12)

EVEN


In [14]:
sub=["java","python","c++","c"]
for x in sub:
    print (x)

java
python
c++
c


In [15]:
for x in "HIRAY":
    print(x)

H
I
R
A
Y


In [17]:
for x in range(10):
    print(x)

0
1
2
3
4
5
6
7
8
9


## Class

In [18]:
class Student:
    name="XYZ"
    marks=20

In [19]:
stud=Student()

In [20]:
print(stud.name)

XYZ


In [21]:
print(stud.marks)

20


In [22]:
class Subjects:
    def __init__(self,name,marks):
        self.name=name
        self.marks=marks

In [23]:
s1 = Subjects("Java",35)

In [24]:
print(s1.name)

Java


In [25]:
print(s1.marks)

35


In [27]:
# enumerate in python
x=["java","python","c++"]
y=enumerate(x)
print(x)

['java', 'python', 'c++']


In [28]:
x=["java","python","c++"]
for i, n in enumerate(x):
    print(n)

java
python
c++


<h3>Implementation of adaline algo for and function. </h3>

In [2]:
import numpy as np

class adaline:
    def __init__(self,in_size, alpha=0.1, ep=100):
        self.alpha = alpha
        self.ep = ep
        self.w = np.zeros(in_size)
        self.b = 0
        
    def act_fun(self, X):
        return X

    def pred(self,X):
        return self.act_fun(np.dot(X,self.w)+self.b)

    def train(self,X,y):
        for e in range(self.ep):
            for i in range(len(X)):
                predi=self.pred(X[i])
                err=y[i]-predi
                #update weights and bias
                self.w+=self.alpha*err*X[i]
                self.b+=self.alpha*err

    def eval(self,X):
        return np.where(self.pred(X)>=0.5,1,0)

X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([0,0,0,1])

a = adaline(in_size=2,alpha=0.1, ep=100)
a.train(X,y)
predictions=a.eval(X)
print(predictions)

[0 0 0 1]


In [3]:
for i, p in enumerate(predictions):
    print(f"Input:{X[i]} => Predicted:{p}=>Actual:{y[i]}")

Input:[0 0] => Predicted:0=>Actual:0
Input:[0 1] => Predicted:0=>Actual:0
Input:[1 0] => Predicted:0=>Actual:0
Input:[1 1] => Predicted:1=>Actual:1
