# Introduction of Numpy library
## We will discuss list,tuple and dictionary before numpy
**Bold**
Numpy library is used to create **Numerical** ***Array***
### we discuss about various data strutures
- List
- Tuple
- Dictonary

In [1]:
numbers=[1,2,3]

In [2]:
type(numbers)

list

In [3]:
#display the first element of number list
numbers[0]

1

In [4]:
numbers=(1,2,3,4)

In [5]:
type(numbers)

tuple

# List is murable and Tuple is Immuable

In [6]:
arr=[1,2,3,4]

In [7]:
arr[0]

1

In [8]:
arr[0]=100

In [9]:
arr[0]

100

In [10]:
arr

[100, 2, 3, 4]

In [11]:
numbers[0]=100

TypeError: 'tuple' object does not support item assignment

In [12]:
arr.append(7)

In [13]:
arr

[100, 2, 3, 4, 7]

In [14]:
a=[1,2,3,4]
b=[3,2,1,0]
add=a+b
print(add)

[1, 2, 3, 4, 3, 2, 1, 0]


##  To perform mathematical oprations on array elemnets we need numerical array
## Numerical type array can be created with help of numpy library

In [15]:
#create numpy array
import numpy as np
#array() is method of numpy
arr=np.array([1,2,3])

In [16]:
arr

array([1, 2, 3])

In [17]:
type(arr)

numpy.ndarray

In [18]:
arr1=np.array([1,2,3,4])
arr2=np.array([4,3,2,1])

In [19]:
arr1+arr2

array([5, 5, 5, 5])

In [20]:
a1=np.array([[1,2,3],[2,3,4],[4,5,6]])

In [21]:
a1

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [22]:
#print shape of array
print(a1.shape)

(3, 3)


In [23]:
print(a1.ndim)

2


In [24]:
print(a1.itemsize)

8


In [25]:
print(a1.dtype)

int64


In [26]:
#create an numarray of float type
#convert the datatype of an array from integer to float
A1=np.array([[1,2],[3,4],[5,6]], dtype=np.float64)
A1[0]

array([1., 2.])

In [27]:
A1=np.array([[1,2],[3,4],[5,6]], dtype=complex)
A1[0]

array([1.+0.j, 2.+0.j])

## 1. Creating arrays from existing data - np.array()

In [29]:
import numpy as np

In [30]:
# 1D array from list
arr1=np.array([10,20,30,40])
print(arr1)

[10 20 30 40]


In [31]:
#print data type of array
print(arr1.dtype)

int64


In [32]:
#2d array(matrix)
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


## 2.Constant field array - np.zeros()-array of all zeros

In [33]:
#np.zeros(rowSize,colSize) #1d zeros
z1=np.zeros(5)
print(z1)
#2d zeros
newArray=np.zeros((2,3))
print(newArray)
#integer zeros
z2=np.zeros((2,3),dtype=int)
print(z2)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]]


## np.ones()-array of all ones

In [34]:
#np.ones(rowSize,colSize) #1d zeros
z3=np.ones((2,3))
print(z3)


[[1. 1. 1.]
 [1. 1. 1.]]


## np.full() - custom fill value - fills an array of any shape

In [35]:
#np.full(size,constValue)
f1=np.full(5,7)
print(f1)
f2=np.full((3,3),(3.14))
print(f2)

[7 7 7 7 7]
[[3.14 3.14 3.14]
 [3.14 3.14 3.14]
 [3.14 3.14 3.14]]


## Range - based arrays
## np.arrange() - works line range()

In [36]:
#arange(stopValue)
ArangeArray=np.arange(6)# if we are only value it will consider stop value
print(ArangeArray)

[0 1 2 3 4 5]


In [37]:
#arange(start,stop)
print(np.arange(1,6))
#arange(start,stop,step)-we can use float also
print(np.arange(0,10,2))

[1 2 3 4 5]
[0 2 4 6 8]


## np.linspace()- it equally spaced and create in it

In [38]:
# 5 values from 0 to 1
print(np.linspace(0,1,5))

# 4 values from 0 to 10
print(np.linspace(0,10,4))

# exclude endpoint
print(np.linspace(0,1,5,endpoint=False))

[0.   0.25 0.5  0.75 1.  ]
[ 0.          3.33333333  6.66666667 10.        ]
[0.  0.2 0.4 0.6 0.8]


## 4. Identity and Diagonal arrays - np.eye()-identity matrix
## creates an NxM matrix with ones on the main diagonal

In [39]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [40]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 5. Random arrays- numpy.random
## numpy's random module provides function to create arrays
## np.random.rand()- Uniform[0, 1]

In [41]:
#1d.5 val;ues uniform between 0 and 1
print(np.random.rand(5))

[0.49219801 0.66450131 0.80185388 0.47604667 0.00757649]


In [42]:
#2d: 2x3 matrix
print(np.random.rand(2,3))

[[0.63158342 0.68015403 0.84108839]
 [0.23881692 0.21927071 0.79377009]]


In [43]:
#np.random.randint() - random integers
# 0 to 9
print(np.random.randint(0,10,size=5))

[0 3 0 4 5]


In [44]:
#2d matrix
print(np.random.randint(1,100,size=(3,3)))

[[70 55 75]
 [75 43 42]
 [68 24 62]]


In [45]:
#uniform b/w 2 and 8
np.random.uniform(2,8,size=5)

array([7.51222514, 3.74175046, 6.204201  , 2.55624608, 2.67156553])

In [46]:
a=np.array([[3,6],[9,12]])
# zeros_like- same shape, all zeros
print(np.zeros_like(a))

[[0 0]
 [0 0]]


In [47]:
print(np.ones_like(a))

print(np.full_like(a,fill_value=89))

[[1 1]
 [1 1]]
[[89 89]
 [89 89]]


In [48]:
# create one 2d array of(2,3) size
a2=np.array([[1,2,3],[4,5,6]])
print(a2)
#find size, datatype,dimension,shape of the created array
print(a2.size)
print(a2.dtype)
print(a2.shape)
print(a2.ndim)

[[1 2 3]
 [4 5 6]]
6
int64
(2, 3)
2


In [49]:
# create an array of elements from 0 to 12
print(np.arange(0,13))
#convert the array elements n 2d array size(3,4)
a=np.arange(12)
a.reshape(3,4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])